Repository TypedDevs/bashunit, pull requests merged in 2023-09, with the labels that each got.

#11 Add MIT license
  LICENSE
Labels: documentation

#13 Add option --filter by test name
  CHANGELOG.md
  src/test_runner.sh
Labels: enhancement

#27 chore: added assert matches, refactor global variables to start with underscored and add watch to the Makefile
  Makefile
  bashunit
  src/assert.sh
  src/console_results.sh
  src/test_runner.sh
  tests/unit/assert_test.sh
Labels: enhancement

#34 fix: Makefile
  Makefile
Labels: bug

#35 Remove Time taken feature from non-Linux
  CHANGELOG.md
  bashunit
  src/assert.sh
  src/console_results.sh
  tests/unit/assert_test.sh
  tests/unit/render_test.sh
Labels: bug

#33 chore: run pipelines on multiple os
  .github/workflows/tests.yml
  Makefile
  src/console_results.sh
  tests/unit/render_test.sh
Labels: enhancement

#40 Listing tests
  .github/CONTRIBUTING.md
  Makefile
  bashunit
  example/README.md
  src/assert.sh
  src/check_os.sh
  src/colors.sh
  src/console_results.sh
  src/env_configuration.sh
  src/test_runner.sh
  tests/unit/assert_test.sh
  tests/unit/console_results_test.sh
  tests/unit/render_test.sh
Labels: enhancement

#42 Prevent framework to be broken if there is not a .env file
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/editor_config_lint.yml
  .github/workflows/tests.yml
  Makefile
  bashunit
  src/default_env_config.sh
  src/env_configuration.sh
Labels: enhancement

#44 Add new logo
  .editorconfig
  README.md
  docs/assets/logo.svg
  docs/assets/logo_name.svg
  docs/assets/logo_name_dark.svg
  docs/assets/social_preview.svg
Labels: documentation

#49 Create assertExitCode
  CHANGELOG.md
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#52 Refactor normalizeFunctionName
  bashunit
  src/assert.sh
  src/helpers.sh
  src/test_runner.sh
  tests/unit/helpers_test.sh
Labels: refactor

#53 Add README.md inside docs/
  docs/README.md
Labels: documentation

#55 Change suggestions
  .github/workflows/static_analysis.yml
  Makefile
  example/README.md
  example/demo_make.png
  example/logic_test.sh
  tests/functional/logic_test.sh
Labels: documentation

#63 fixing test, creating assertSuccessfulCode assertGeneralError assertCommandNotFound
  CHANGELOG.md
  Makefile
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#64 Update LICENSE to include all main contributors from TypedDevs
  LICENSE
Labels: documentation

#66 Fix error on count assertions
  CHANGELOG.md
  src/test_runner.sh
  tests/unit/console_results_test.sh
Labels: bug

#58 Throw error on duplicated tests
  src/helpers.sh
  src/test_runner.sh
  tests/unit/helpers_test.sh
Labels: enhancement

#91 Improve doc index features
  docs/index.md
Labels: documentation

#88 Add docs setup in CONTRIBUTING.md
  .github/CONTRIBUTING.md
Labels: documentation

#92 add setUp, setUpBeforeScript, tearDown and tearDownAfterScript functions execution
  CHANGELOG.md
  src/helpers.sh
  src/runner.sh
  tests/unit/helpers_test.sh
  tests/unit/setup_teardown_test.sh
Labels: enhancement

#94 Unset setup functions
  src/assert.sh
  src/helpers.sh
  src/runner.sh
  tests/unit/helpers_test.sh
Labels: bug

#95 Add namespace function names
  src/assert.sh
  src/console_results.sh
  src/helpers.sh
  src/runner.sh
  tests/unit/assert_test.sh
  tests/unit/console_results_test.sh
  tests/unit/helpers_test.sh
Labels: enhancement

#90 Add bpkg.json
  bpkg.json
Labels: documentation

#97 Homepage
  docs/.vitepress/theme/style.css
  docs/index.md
  docs/public/accessible.svg
  docs/public/flexible.svg
  docs/public/logo.svg
  docs/public/logo_name.svg
  docs/public/logo_name_dark.svg
  docs/public/multiplatform.svg
  docs/public/updated.svg
  package.json
  yarn.lock
Labels: documentation

#98 Favicon + SEO + small things
  docs/.vitepress/config.ts
  docs/public/favicon.ico
  docs/public/favicon.svg
  docs/public/logo_navbar.svg
  docs/public/logo_navbar_dark.svg
Labels: documentation

#96 Add docs for assertEmpty and assertNotEmpty
  docs/assertions.md
Labels: documentation

#99 Fix hero image tilt
  docs/.vitepress/theme/style.css
  docs/index.md
Labels: bug

#102 Use xhofe/gh-contributors so no workflow required
  .github/workflows/contributors.yml
  README.md
  docs/public/contributors.svg
Labels: documentation

#82 Fix async
  .env.example
  bashunit
  bin/pre-commit
  src/assert.sh
  src/check_os.sh
  src/console_results.sh
  src/default_env_config.sh
  src/env_configuration.sh
  src/runner.sh
  src/state.sh
  tests/acceptance/bashunit_test.sh
Labels: bug

#103 .md indentation
  .editorconfig
  .github/CONTRIBUTING.md
  .github/workflows/static_analysis.yml
  Makefile
  README.md
  example/README.md
  example/demo.png
  example/demo_make.png
Labels: documentation

#101 Stop runner when found duplicate functions
  CHANGELOG.md
  bashunit
  src/console_results.sh
  src/helpers.sh
  src/runner.sh
  src/state.sh
  tests/acceptance/bashunit_test.sh
  tests/unit/fixtures/duplicate_functions.sh
  tests/unit/fixtures/no_duplicate_functions.sh
  tests/unit/helpers_test.sh
  tests/unit/setup_teardown_test.sh
Labels: enhancement

#104 Refactor loadTestFiles to receive args instead of using globals
  src/runner.sh
Labels: refactor

#107 Add how to install to docs
  README.md
  docs/.vitepress/config.ts
  docs/.vitepress/theme/style.css
  docs/examples.md
  docs/getting-started.md
  example/README.md
  example/demo.png
  example/demo_make.png
  example/logic_test.sh
Labels: documentation

#111 Make boxes slightly less dark for the bashunit webpage
  docs/.vitepress/theme/style.css
Labels: documentation

#112 Doc test files
  docs/.vitepress/config.ts
  docs/.vitepress/theme/style.css
  docs/test-files.md
  yarn.lock
Labels: documentation

#113 Enable sitemap.xml generation
  .editorconfig
  docs/.vitepress/config.ts
Labels: documentation

#119 chore: add spy and assertHaveBeenCalledTimes assertHaveBeenCalled ass…
  CHANGELOG.md
  bashunit
  src/assert.sh
  src/test_doubles.sh
  tests/unit/fake_test.sh
  tests/unit/test_doubles_test.sh
Labels: enhancement

#118 Extract main from runner.sh to bashunit
  bashunit
  src/runner.sh
Labels: refactor

#121 Create one single bin executable
  .gitignore
  install.sh
Labels: enhancement

#120 Use snake_case assertions
  CHANGELOG.md
  docs/assertions.md
  docs/getting-started.md
  example/logic_test.sh
  src/assert.sh
  src/test_doubles.sh
  tests/acceptance/bashunit_test.sh
  tests/functional/logic_test.sh
  tests/unit/assert_test.sh
  tests/unit/console_results_test.sh
  tests/unit/helpers_test.sh
  tests/unit/setup_teardown_test.sh
  tests/unit/test_doubles_test.sh
Labels: enhancement

#109 Manage error when test execution fails
  CHANGELOG.md
  src/console_results.sh
  src/helpers.sh
  src/runner.sh
  src/state.sh
  src/test_doubles.sh
  tests/acceptance/bashunit_test.sh
  tests/functional/logic_test.sh
  tests/unit/assert_test.sh
  tests/unit/helpers_test.sh
  tests/unit/state_test.sh
Labels: enhancement

#124 Output dots
  CHANGELOG.md
  bashunit
  bin/pre-commit
  src/console_results.sh
  src/runner.sh
  tests/acceptance/bashunit_test.sh
Labels: enhancement

#125 Install and build scripts
  CHANGELOG.md
  build.sh
  install.sh
Labels: enhancement

#126 Use verbose output by default
  CHANGELOG.md
  Makefile
  bashunit
  src/console_results.sh
  src/runner.sh
  tests/acceptance/bashunit_test.sh
Labels: enhancement
