Repository TypedDevs/bashunit, pull requests merged in 2023-10, with the labels that each got.

#127 Add mocks docs
  docs/.vitepress/config.ts
  docs/getting-started.md
  docs/test-doubles.md
Labels: documentation

#130 Docs for files asserts
  docs/assertions.md
Labels: documentation

#131 Little test doubles changes
  docs/.vitepress/config.ts
  docs/test-doubles.md
  src/test_doubles.sh
  tests/unit/test_doubles_test.sh
Labels: documentation

#129 Add assert for directory
  CHANGELOG.md
  docs/assertions.md
  src/assert.sh
  tests/unit/directory_test.sh
Labels: enhancement

#134 Rename set_up/tear_down functions from camelCase to snake_case
  CHANGELOG.md
  docs/test-files.md
  src/runner.sh
  tests/unit/setup_teardown_test.sh
Labels: refactor

#135 Refactor state functions
  bashunit
  src/assert.sh
  src/console_results.sh
  src/helpers.sh
  src/runner.sh
  src/state.sh
  src/test_doubles.sh
  tests/unit/state_test.sh
Labels: refactor

#137 Unset setUp and tearDown scripts after script execution
  src/runner.sh
Labels: bug

#138 Add --version
  .editorconfig
  .env.example
  CHANGELOG.md
  bashunit
  src/assert.sh
  src/console_header.sh
  src/console_results.sh
  src/default_env_config.sh
  src/deprecated_assert.sh
  src/env_configuration.sh
  src/helpers.sh
  src/runner.sh
  src/test_doubles.sh
  tests/acceptance/bashunit_test.sh
  tests/unit/assert_test.sh
  tests/unit/console_results_test.sh
  tests/unit/directory_test.sh
  tests/unit/file_test.sh
  tests/unit/helpers_test.sh
  tests/unit/test_doubles_test.sh
Labels: enhancement

#140 Find all test on a directory
  CHANGELOG.md
  bashunit
  docs/getting-started.md
  docs/test-files.md
  src/helpers.sh
Labels: enhancement

#141 Minor output changes
  src/assert.sh
  src/colors.sh
  src/console_header.sh
  src/console_results.sh
  src/runner.sh
  src/test_doubles.sh
  tests/acceptance/bashunit_test.sh
  tests/unit/assert_test.sh
  tests/unit/directory_test.sh
  tests/unit/file_test.sh
  tests/unit/helpers_test.sh
  tests/unit/test_doubles_test.sh
Labels: refactor

#149 fix: installer default version
  install.sh
Labels: bug

#145 Skip tests
  CHANGELOG.md
  bashunit
  docs/.vitepress/config.ts
  docs/skipping-tests.md
  src/colors.sh
  src/console_header.sh
  src/console_results.sh
  src/helpers.sh
  src/runner.sh
  src/skip.sh
  src/state.sh
  src/test_doubles.sh
  tests/acceptance/bashunit_test.sh
  tests/unit/console_results_test.sh
  tests/unit/fixtures/duplicate_functions.sh
  tests/unit/fixtures/no_duplicate_functions.sh
  tests/unit/helpers_test.sh
  tests/unit/skip_test.sh
  tests/unit/state_test.sh
Labels: enhancement

#150 Incomplete tests
  CHANGELOG.md
  bashunit
  docs/.vitepress/config.ts
  docs/skipping-incomplete.md
  docs/skipping-tests.md
  src/colors.sh
  src/console_results.sh
  src/runner.sh
  src/skip_todo.sh
  src/state.sh
  tests/unit/console_results_test.sh
  tests/unit/skip_test.sh
  tests/unit/skip_todo_test.sh
  tests/unit/state_test.sh
Labels: enhancement

#151 feat: env simple output
  bashunit
  src/console_results.sh
  src/default_env_config.sh
  src/env_configuration.sh
  src/runner.sh
  tests/acceptance/bashunit_test.sh
Labels: enhancement

#153 Allow using main or latest when using install.sh
  CHANGELOG.md
  install.sh
Labels: enhancement

#156 Simplify Getting started
  docs/.vitepress/config.ts
  docs/command-line.md
  docs/getting-started.md
  docs/installation.md
  docs/support.md
Labels: documentation

#157 Create RELEASE documentation
  .github/RELEASE.md
Labels: documentation

#155 Serve fonts from origin instead of cdn
  CHANGELOG.md
  docs/.vitepress/theme/fonts.css
  docs/.vitepress/theme/style.css
  docs/public/fonts/Cousine-Regular.ttf
  docs/public/fonts/Heebo-Regular.ttf
  docs/public/fonts/Heebo-SemiBold.ttf
  docs/public/fonts/Rubik-SemiBold.ttf
Labels: documentation, hacktoberfest

#158 docs: add tooltip in installation page
  docs/installation.md
Labels: documentation

#163 Add footer links
  docs/.vitepress/theme/style.css
Labels: documentation

#167 Add last updated
  docs/.vitepress/config.ts
Labels: documentation

#164 Add code-groups
  docs/assertions.md
  docs/command-line.md
  docs/quickstart.md
  docs/skipping-incomplete.md
  docs/test-doubles.md
  docs/test-files.md
Labels: documentation

#165 Add edit link
  docs/.vitepress/config.ts
Labels: documentation

#166 Small docs fixes
  docs/installation.md
Labels: documentation

#186 chore: separate asserts on different files
  bashunit
  src/assert.sh
  src/assert_arrays.sh
  src/assert_files.sh
  src/assert_folders.sh
  src/assertions.sh
Labels: refactor

#188 Assert string ends with
  CHANGELOG.md
  docs/assertions.md
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#189 feat: alternative to set -e
  adrs/TEMPLATE.md
  adrs/adr-001-changing-error-detection-mechanism.md
  src/console_results.sh
  src/runner.sh
  tests/acceptance/bashunit_test.sh
Labels: bug, enhancement

#169 Add blog posts to website
  CHANGELOG.md
  docs/.vitepress/config.ts
  docs/.vitepress/theme/index.ts
  docs/.vitepress/theme/style.css
  docs/.vitepress/tsconfig.json
  docs/blog/0000-00-00-template.md
  docs/blog/PostCard.vue
  docs/blog/index.md
  docs/blog/posts.data.ts
  docs/index.md
  package.json
  yarn.lock
Labels: documentation, enhancement

#192 Define a custom .env when running bashunit
  CHANGELOG.md
  bashunit
  docs/command-line.md
  src/console_header.sh
  tests/acceptance/.env.verbose
  tests/acceptance/bashunit_test.sh
Labels: enhancement

#184 Add --stop-on-failure option
  .env.example
  CHANGELOG.md
  bashunit
  docs/command-line.md
  src/console_header.sh
  src/default_env_config.sh
  src/env_configuration.sh
  src/runner.sh
  tests/acceptance/bashunit_test.sh
  tests/acceptance/fixtures/stop_on_failure.sh
Labels: enhancement

#193 Asserts less|greater [or equal] than
  CHANGELOG.md
  docs/assertions.md
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#195 Fix and test installer
  .github/RELEASE.md
  CHANGELOG.md
  docs/quickstart.md
  install.sh
  tests/acceptance/install_test.sh
Labels: bug, enhancement

#197 docs: add MacPorts install info
  docs/installation.md
Labels: documentation, enhancement

#196 chore: assert_contains_ignore_case
  CHANGELOG.md
  docs/assertions.md
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#199 Add assert_equals_ignore_colors
  CHANGELOG.md
  docs/assertions.md
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#201 Show execution time
  .env.example
  CHANGELOG.md
  package.json
  src/console_results.sh
  src/default_env_config.sh
  src/env_configuration.sh
  tests/unit/console_results_test.sh
  yarn.lock
Labels: enhancement

#198 Assert match snapshot
  CHANGELOG.md
  docs/.vitepress/config.ts
  docs/snapshots.md
  src/assert_snapshot.sh
  src/assertions.sh
  src/console_results.sh
  tests/unit/assert_snapshot_test.sh
  tests/unit/snapshots/.gitignore
  tests/unit/snapshots/assert_snapshot_test_sh.test_unsuccessful_assert_match_snapshot.snapshot
Labels: enhancement

#202 Add docs for env config
  CHANGELOG.md
  docs/.vitepress/config.ts
  docs/command-line.md
  docs/configuration.md
Labels: documentation

#204 Improve data provider output
  CHANGELOG.md
  src/console_results.sh
  src/runner.sh
  tests/unit/console_results_test.sh
Labels: enhancement

#207 Add description to README.md
  README.md
Labels: documentation

#209 Fix wildcards tests
  Makefile
  bashunit
  src/helpers.sh
  src/runner.sh
  tests/unit/helpers_test.sh
Labels: bug

#206 #114 - Output of the duplicated test it's not understandable
  CHANGELOG.md
  src/console_results.sh
  src/helpers.sh
  src/state.sh
  tests/unit/console_results_test.sh
  tests/unit/state_test.sh
Labels: enhancement
