Repository TypedDevs/bashunit, pull requests merged in 2023-11, with the labels that each got.

#216 Docs greater less than
  .github/ISSUE_TEMPLATE/BUG.md
  docs/assertions.md
  docs/command-line.md
  docs/configuration.md
  docs/quickstart.md
  package.json
  yarn.lock
Labels: documentation

#218 Snapshots iteration 2
  docs/snapshots.md
  src/assert_snapshot.sh
  src/colors.sh
  src/console_results.sh
  src/runner.sh
  src/state.sh
  tests/unit/assert_snapshot_test.sh
  tests/unit/console_results_test.sh
  tests/unit/snapshots/.gitignore
  tests/unit/snapshots/assert_snapshot_test_sh.test_successful_assert_match_snapshot.snapshot
  tests/unit/state_test.sh
Labels: enhancement

#219 Fix test_creates_a_snapshot for macOS
  tests/unit/assert_snapshot_test.sh
Labels: bug

#211 Allow install beta
  CHANGELOG.md
  build.sh
  docs/installation.md
  install.sh
  tests/acceptance/install_test.sh
Labels: enhancement

#221 Fix find tests inside folder
  CHANGELOG.md
  src/console_results.sh
  src/helpers.sh
  src/runner.sh
  tests/acceptance/bashunit_find_tests_command_line_test.sh
  tests/acceptance/bashunit_path_test.sh
  tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_with_wildcard.snapshot
  tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_within_a_directory.snapshot
  tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_within_a_file.snapshot
  tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_argument_overloads_default_path.snapshot
  tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_with_argument_path.snapshot
  tests/unit/console_results_test.sh
  tests/unit/fixtures/tests/example1_test.sh
  tests/unit/fixtures/tests/example2_test.sh
  tests/unit/helpers_test.sh
Labels: bug

#223 Update docs node and yarn version
  .github/CONTRIBUTING.md
  .github/workflows/check-docs.yml
  .github/workflows/deploy-docs.yml
  .gitignore
  .nvmrc
  .yarn/releases/yarn-4.0.1.cjs
  .yarnrc.yml
  package.json
  yarn.lock
Labels: documentation

#224 Add current date on beta installation version
  CHANGELOG.md
  install.sh
  tests/acceptance/install_test.sh
Labels: enhancement

#226 docs: add codelytv post
  docs/blog/2023-11-15-bashunit-live-on-codelytv.md
  docs/public/covers/2023-11-15-bashunit-live-on-codelytv.jpg
Labels: documentation

#228 Optimize bashunit
  src/helpers.sh
  src/runner.sh
Labels: enhancement

#230 docs: Remove Git submodule
  docs/installation.md
Labels: documentation

#231 Add fizzbuzz kata to examples.md
  docs/examples.md
Labels: documentation
