Repository TypedDevs/bashunit, pull requests merged in 2024-10, with the labels that each got.

#344 Remove deprecated assertions
  CHANGELOG.md
  src/assertions.sh
  src/deprecated_assert.sh
Labels: enhancement

#345 feature: remove curl perl and coreutils as required dependencies
  .github/CONTRIBUTING.md
  .github/workflows/tests.yml
  CHANGELOG.md
  Makefile
  bashunit
  install.sh
  src/check_os.sh
  src/clock.sh
  src/console_results.sh
  src/dependencies.sh
  src/io.sh
  src/math.sh
  src/runner.sh
  src/upgrade.sh
  tests/globals.sh
  tests/unit/assert_snapshot_test.sh
  tests/unit/check_os_test.sh
  tests/unit/clock_test.sh
  tests/unit/console_results_test.sh
  tests/unit/dependencies_test.sh
Labels: enhancement

#346 Normalize boolean syntax
  .env.example
  adrs/adr-002-using-booleans.md
  bashunit
  src/console_header.sh
  src/console_results.sh
  src/default_env_config.sh
  src/env.sh
  src/env_configuration.sh
  src/runner.sh
  src/state.sh
  tests/acceptance/fixtures/.env.default
  tests/acceptance/fixtures/.env.log_junit
  tests/acceptance/fixtures/.env.report_html
  tests/acceptance/fixtures/.env.simple
  tests/acceptance/fixtures/.env.stop_on_failure
  tests/acceptance/fixtures/.env.with_path
Labels: enhancement

#348 Log info into file
  .gitignore
  CHANGELOG.md
  docs/assertions.md
  docs/configuration.md
  docs/globals.md
  src/assert_files.sh
  src/env.sh
  src/globals.sh
  tests/unit/file_test.sh
  tests/unit/globals_test.sh
Labels: enhancement

#349 Better cleanup temporal files
  CHANGELOG.md
  src/globals.sh
  src/main.sh
  tests/acceptance/bashunit_direct_fn_call_test.sh
  tests/unit/directory_test.sh
Labels: refactoring

#350 Add assert_true and assert_false
  CHANGELOG.md
  docs/assertions.md
  src/assert.sh
  tests/unit/assert_test.sh
  tests/unit/state_test.sh
Labels: enhancement

#351 Add bashdep to installation
  docs/installation.md
Labels: documentation

#352 Improve assert true/false accepting callable as arg
  docs/assertions.md
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#353 Improve CI tests runtime (halved)
  .github/workflows/tests.yml
  CHANGELOG.md
  src/console_results.sh
  tests/unit/console_results_test.sh
  tests/unit/globals_test.sh
Labels: refactoring

#355 fix: use mktemp compatible bash 3.2
  src/globals.sh
Labels: bug, pure testing

#356 Add some default env values
  .github/workflows/tests.yml
  CHANGELOG.md
  src/env.sh
Labels: enhancement

#358 Running in parallel
  .env.example
  .github/workflows/tests.yml
  CHANGELOG.md
  Makefile
  adrs/adr-003-parallel-testing.md
  bashunit
  docs/command-line.md
  docs/configuration.md
  src/console_header.sh
  src/env.sh
  src/globals.sh
  src/main.sh
  src/parallel.sh
  src/runner.sh
  src/state.sh
  tests/acceptance/bashunit_direct_fn_call_test.sh
  tests/acceptance/bashunit_execution_error_test.sh
  tests/acceptance/bashunit_fail_test.sh
  tests/acceptance/bashunit_find_tests_command_line_test.sh
  tests/acceptance/bashunit_log_junit_test.sh
  tests/acceptance/bashunit_pass_test.sh
  tests/acceptance/bashunit_path_test.sh
  tests/acceptance/bashunit_report_html_test.sh
  tests/acceptance/bashunit_stop_on_failure_test.sh
  tests/acceptance/bashunit_test.sh
  tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_without_path_env_nor_argument.snapshot
  tests/acceptance/snapshots/bashunit_test_sh.test_bashunit_should_display_help.snapshot
  tests/functional/provider_test.sh
  tests/unit/directory_test.sh
  tests/unit/state_test.sh
Labels: enhancement

#361 Rename logger.sh to reports.sh
  bashunit
  src/main.sh
  src/reports.sh
  src/runner.sh
Labels: refactoring

#362 Display seconds on time taken
  CHANGELOG.md
  src/console_results.sh
  tests/unit/console_results_test.sh
Labels: enhancement

#364 Improve build
  build.sh
  tests/unit/debug_test.sh
Labels: refactoring

#365 Improve installer
  .github/RELEASE.md
  CHANGELOG.md
  install.sh
  tests/acceptance/install_test.sh
Labels: enhancement

#369 Rename verbose to detailed
  .env.example
  .gitignore
  CHANGELOG.md
  bashunit
  docs/command-line.md
  docs/configuration.md
  docs/globals.md
  src/console_header.sh
  src/env.sh
  src/globals.sh
  tests/acceptance/bashunit_fail_test.sh
  tests/acceptance/bashunit_pass_test.sh
  tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_without_path_env_nor_argument.snapshot
  tests/acceptance/snapshots/bashunit_test_sh.test_bashunit_should_display_help.snapshot
  tests/unit/globals_test.sh
Labels: enhancement

#373 Fix tr warning on ubuntu's CI
  src/globals.sh
  src/runner.sh
  src/state.sh
  tests/unit/state_test.sh
Labels: bug

#374 Verbose option
  CHANGELOG.md
  bashunit
  docs/command-line.md
  docs/configuration.md
  src/console_header.sh
  src/env.sh
  src/runner.sh
  tests/acceptance/fixtures/.env.default
  tests/acceptance/fixtures/.env.log_junit
  tests/acceptance/fixtures/.env.report_html
  tests/acceptance/fixtures/.env.simple
  tests/acceptance/fixtures/.env.stop_on_failure
  tests/acceptance/fixtures/.env.with_path
  tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_without_path_env_nor_argument.snapshot
  tests/acceptance/snapshots/bashunit_test_sh.test_bashunit_should_display_help.snapshot
Labels: enhancement

#375 Add verbose information to test suite
  src/env.sh
  src/main.sh
Labels: enhancement

#376 Improve render file header on verbose
  src/runner.sh
  tests/acceptance/bashunit_execution_error_test.sh
  tests/acceptance/fixtures/test_bashunit_when_a_execution_error.sh
  tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_env.snapshot
  tests/acceptance/snapshots/bashunit_fail_test_sh.test_bashunit_when_a_test_fail_verbose_output_option.snapshot
  tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_with_wildcard.snapshot
  tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_within_a_directory.snapshot
  tests/acceptance/snapshots/bashunit_find_tests_command_line_test_sh.test_all_tests_files_within_a_file.snapshot
  tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_env.snapshot
  tests/acceptance/snapshots/bashunit_log_junit_test_sh.test_bashunit_when_log_junit_option.snapshot
  tests/acceptance/snapshots/bashunit_pass_test_sh.test_bashunit_when_a_test_passes_verbose_output_env.snapshot
  tests/acceptance/snapshots/bashunit_pass_test_sh.test_bashunit_when_a_test_passes_verbose_output_option.snapshot
  tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_with_argument_path.snapshot
  tests/acceptance/snapshots/bashunit_path_test_sh.test_bashunit_with_env_default_path.snapshot
  tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_env.snapshot
  tests/acceptance/snapshots/bashunit_report_html_test_sh.test_bashunit_when_report_html_option.snapshot
  tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_env.snapshot
  tests/acceptance/snapshots/bashunit_stop_on_failure_test_sh.test_bashunit_when_stop_on_failure_option.snapshot
Labels: enhancement
