Repository TypedDevs/bashunit, pull requests merged in 2024-08, with the labels that each got.

#303 Remove deprecated uppercase methods on state_test file
  tests/unit/state_test.sh
Labels: refactoring

#304 Remove ProductHunt & Manfred Awards from index
  docs/ProductHuntBanner.vue
  docs/index.md
Labels: documentation

#307 Prefix all .env config keys with `BASHUNIT_`
  .env.example
  CHANGELOG.md
  bashunit
  docs/command-line.md
  docs/configuration.md
  src/console_header.sh
  src/console_results.sh
  src/env_configuration.sh
  src/main.sh
  src/runner.sh
  tests/acceptance/bashunit_log_junit_test.sh
  tests/acceptance/fixtures/.env.default
  tests/acceptance/fixtures/.env.log_junit
  tests/acceptance/fixtures/.env.report_html
  tests/acceptance/fixtures/.env.simple
  tests/acceptance/fixtures/.env.stop_on_failure
  tests/acceptance/fixtures/.env.with_path
  tests/unit/console_results_test.sh
Labels: enhancement

#310 Sort parameterized tests
  docs/parameterized-tests.md
Labels: documentation
