Repository TypedDevs/bashunit, pull requests merged in 2024-06, with the labels that each got.

#259 Add `assert_line_count`
  CHANGELOG.md
  docs/assertions.md
  src/assert.sh
  tests/unit/assert_test.sh
Labels: enhancement

#260 Add LATEST_BASHUNIT_VERSION when installing beta
  CHANGELOG.md
  install.sh
  tests/acceptance/install_test.sh
Labels: enhancement

#262 Improve assert function standalone
  src/main.sh
  tests/acceptance/snapshots/bashunit_direct_fn_call_test_sh.test_bashunit_direct_fn_call_failure.snapshot
Labels: bug

#264 Fix: assert_line_count
  src/assert.sh
  tests/unit/assert_test.sh
Labels: bug

#265 fix: assert_line_count on multiline
  src/assert.sh
  src/main.sh
  tests/acceptance/bashunit_direct_fn_call_test.sh
  tests/acceptance/snapshots/bashunit_direct_fn_call_test_sh.test_bashunit_direct_fn_call_failure.snapshot
Labels: bug

#266 Fix: multistring assertions
  src/assert.sh
  tests/acceptance/bashunit_direct_fn_call_test.sh
Labels: bug

#267 Add hash next to version in beta
  CHANGELOG.md
  install.sh
  tests/acceptance/install_test.sh
Labels: enhancement

#268 Add GitHub Actions to installation doc
  CHANGELOG.md
  docs/installation.md
Labels: documentation

#270 Fix: exit code when fn does not exist
  src/main.sh
  tests/acceptance/bashunit_direct_fn_call_test.sh
Labels: bug

#271 Minor docs style improvements
  docs/command-line.md
  docs/configuration.md
  docs/standalone.md
Labels: documentation

#273 Add PHPStan integration (blog post)
  docs/blog/2024-06-21-phpstan-integration.md
  docs/public/covers/2024-06-21-phpstan-integration.jpg
Labels: documentation

#274 Test: redirect file descriptor error
  tests/unit/redirect_error_test.sh
Labels: pure testing

#275 fix: echo does not break test execution result
  CHANGELOG.md
  src/runner.sh
  tests/unit/redirect_error_test.sh
Labels: bug
