Repository TypedDevs/bashunit, pull requests merged in 2025-06, with the labels that each got.

#417 docs/fix: interpolate frontmatter variables during local search index generation
  docs/.vitepress/config.ts
Labels: bug, documentation

#423 Support placeholder ignore in snapshots
  CHANGELOG.md
  docs/snapshots.md
  src/assert_snapshot.sh
  tests/unit/assert_snapshot_test.sh
Labels: enhancement

#422 Add benchmark feature
  CHANGELOG.md
  bashunit
  docs/.vitepress/config.ts
  docs/benchmarks.md
  docs/command-line.md
  docs/configuration.md
  src/benchmark.sh
  src/helpers.sh
  src/main.sh
  src/runner.sh
  tests/acceptance/snapshots/bashunit_benchmark_test_sh.test_bashunit_functional_benchmark.snapshot
  tests/acceptance/snapshots/bashunit_benchmark_test_sh.test_bashunit_runs_benchmark_file.snapshot
  tests/benchmark/bashunit_bench.sh
  tests/benchmark/fixtures/.env.with_path
  tests/benchmark/fixtures/bashunit_functional_bench.sh
  tests/benchmark/fixtures/bashunit_sleep_bench.sh
  tests/functional/for_bench_test.sh
  tests/unit/assert_snapshot_test.sh
  tests/unit/benchmark_test.sh
Labels: enhancement

#424 Add max_ms option on bench
  bashunit
  docs/benchmarks.md
  src/benchmark.sh
  src/env.sh
  src/globals.sh
  src/runner.sh
  tests/benchmark/bashunit_bench.sh
  tests/benchmark/fixtures/bashunit_functional_bench.sh
  tests/benchmark/fixtures/bashunit_sleep_bench.sh
  tests/unit/benchmark_test.sh
Labels: enhancement

#425 Improve bench loading
  bashunit
  src/benchmark.sh
  tests/unit/benchmark_test.sh
Labels: enhancement

#426 Add project overview to website
  CHANGELOG.md
  docs/.vitepress/config.ts
  docs/project-overview.md
Labels: documentation

#427 Improve clock performance
  CHANGELOG.md
  src/clock.sh
  tests/unit/clock_test.sh
Labels: refactoring

#428 Make installer args more flexible
  CHANGELOG.md
  docs/installation.md
  install.sh
  tests/acceptance/install_test.sh
Labels: enhancement

#431 Improve Windows detection for parallel tests
  CHANGELOG.md
  src/check_os.sh
  tests/unit/check_os_test.sh
Labels: enhancement, codex

#434 Fix parallel consistency on arch64
  CHANGELOG.md
  src/runner.sh
Labels: bug

#435 Split macos and ubuntu ci jobs
  .github/workflows/tests.yml
  CHANGELOG.md
Labels: pure testing
