Repository TypedDevs/bashunit, pull requests merged in 2025-09, with the labels that each got.

#481 Doc workaround for global name collisions
  CHANGELOG.md
  docs/globals.md
Labels: documentation

#483 Always correctly clean up temp contents
  CHANGELOG.md
  docs/globals.md
  src/globals.sh
  src/helpers.sh
  src/main.sh
  src/runner.sh
  tests/acceptance/bashunit_script_temp_file_cleanup_test.sh
  tests/acceptance/fixtures/script_with_setup_temp_file.sh
  tests/unit/globals_test.sh
Labels: bug

#484 Fix: clean parallel temp folder after test run
  CHANGELOG.md
  src/main.sh
  src/parallel.sh
  tests/acceptance/bashunit_script_temp_file_cleanup_test.sh
Labels: bug

#488 chore: add copilot-instructions.md for the repo
  .gitattributes
  .github/copilot-instructions.md
  .gitignore
  .tasks/.gitkeep
  AGENTS.md
  CHANGELOG.md
  README.md
  adrs/adr-005-copilot-instruction-or-spec-kit.md
Labels: enhancement

#491 Fix setup and teardown functions when errors
  CHANGELOG.md
  docs/test-files.md
  src/helpers.sh
  src/runner.sh
  src/state.sh
  tests/acceptance/bashunit_setup_before_script_error_test.sh
  tests/acceptance/bashunit_setup_error_test.sh
  tests/acceptance/bashunit_teardown_after_script_error_test.sh
  tests/acceptance/bashunit_teardown_error_test.sh
  tests/acceptance/fixtures/test_bashunit_when_setup_before_script_errors.sh
  tests/acceptance/fixtures/test_bashunit_when_setup_errors.sh
  tests/acceptance/fixtures/test_bashunit_when_teardown_after_script_errors.sh
  tests/acceptance/fixtures/test_bashunit_when_teardown_errors.sh
  tests/unit/globals_test.sh
  tests/unit/redirect_error_test.sh
  tests/unit/state_test.sh
Labels: bug
